force-app/main/default/objects/ProductPricing__c/ProductPricing__c.object-meta.xml
<CustomObject>
    <label>Product Pricing</label>
    <nameField>
        <label>Product Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductPricing__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <label>ATM Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/CalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CalendarMonth__c</fullName>
    <label>Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/CardReplacement__c.field-meta.xml
<CustomField>
    <fullName>CardReplacement__c</fullName>
    <label>Card Replacement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <formula>CASE(  Home_Country__c , &quot;DE&quot;,&quot;€&quot;,&quot;FR&quot;,&quot;€&quot;,&quot;ES&quot;,&quot;€&quot;,&quot;IT&quot;,&quot;€&quot;, &quot;UK&quot;,&quot;£&quot;, &quot;$&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Symbol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Pricing</relationshipLabel>
    <relationshipName>Products_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingInfo.cls
/**
 * Pricing information Wrapper Class
 * Encapsulates product pricing data
 */
public class PricingInfo {
    @AuraEnabled public String calendarMonth;
    @AuraEnabled public String atmFee;
    @AuraEnabled public String cardReplacement;
    @AuraEnabled public String product;
    @AuraEnabled public Id productId;
    @AuraEnabled public String homeCountry;
    
    public PricingInfo(ProductPricing__c pricing) {
        this.calendarMonth =pricing.CalendarMonth__c!= null ? pricing.Currency_Symbol__c +' '+ pricing.CalendarMonth__c.format() : 'N/A';
        this.atmFee = (pricing.ATMFee__c != null && pricing.ATMFee__c != 0)? pricing.ATMFee__c.format() + '%' : 'Free';
        this.cardReplacement = pricing.CardReplacement__c!= null ? pricing.Currency_Symbol__c+' '+pricing.CardReplacement__c.format() : 'N/A';
        this.product = pricing.Product__r.Name;
        this.productId = pricing.Product__c;
        this.homeCountry = pricing.Home_Country__c;
    }
}