force-app/main/default/objects/Contact/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <externalId>true</externalId>
    <label>External UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactSelector.cls
/**
 * @description       : Selector class for all Contact object.
 * @author            : Shahrukh Ahmed
 * @company           : N26
 * @last modified on  : 09-12-2025
 * @last modified by  : Shahrukh Ahmed
 **/
public with sharing class ContactSelector {
    
    /**
     * @Description Finds contact by UUID
     * @auther Shahrukh Ahmed
     * @param uuid - External UUID of the contact
     * @return List<Contact> - List of contacts matching the UUID
     */
    public static List<Contact> selectByUuid(String uuid) {
        
        if (String.isBlank(uuid)) {
            return new List<Contact>();
        }
        
        List<Contact> contact = [
            SELECT Id, Name, Product__c, Home_Country__c, 
                    External_UUID__c
            FROM Contact 
            WHERE External_UUID__c = :uuid 
            AND IsDeleted = false
            WITH USER_MODE 
            LIMIT 1
        ];
        
        return contact;
    }
}