force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/ProductPricing__c.object-meta.xml
<CustomObject>
    <label>Product Pricing</label>
    <nameField>
        <label>Product Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductPricing__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <label>ATM Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/CalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CalendarMonth__c</fullName>
    <label>Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/CardReplacement__c.field-meta.xml
<CustomField>
    <fullName>CardReplacement__c</fullName>
    <label>Card Replacement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <formula>CASE(  Home_Country__c , &quot;DE&quot;,&quot;€&quot;,&quot;FR&quot;,&quot;€&quot;,&quot;ES&quot;,&quot;€&quot;,&quot;IT&quot;,&quot;€&quot;, &quot;UK&quot;,&quot;£&quot;, &quot;$&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Symbol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductPricing__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Pricing</relationshipLabel>
    <relationshipName>Products_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductPricingSelector.cls
/**
 * @description       : Selector class for all ProductPricing__c object.
 * @author            : Shahrukh Ahmed
 * @company           : N26
 * @last modified on  : 09-12-2025
 * @last modified by  : Shahrukh Ahmed
 **/
public with sharing class ProductPricingSelector {
    
    /**
     * @Description Gets pricing information for a contact
     * @auther Shahrukh Ahmed
     * @param productId - Product Id
     * @param homeCountry - Home Country of the contact
     * @return List<ProductPricing__c> - List of pricing information
     */
    public static List<ProductPricing__c> selectByProductAndCountry(Id productId, String homeCountry) {
        
        if (String.isBlank(productId) ||
        String.isBlank(homeCountry)) {
            return new List<ProductPricing__c>();
        }
        List<ProductPricing__c> pricingRecords = [
            SELECT Id, CalendarMonth__c, ATMFee__c, CardReplacement__c, Currency_Symbol__c, ProductPricing__c.Product__r.Name,
                   Product__c, Home_Country__c
            FROM ProductPricing__c 
            WHERE Product__c = :productId 
            AND Home_Country__c = :homeCountry
            WITH USER_MODE
            LIMIT 1000
        ];
        
        return pricingRecords;
    }
}